"""Agentic capsule for the telemetry CLI.

Emits a compact, LLM-consumable summary of the CLI surface. Follows the same
shape as the argparse siblings: ``agentic:`` header, ``purpose:``, ``commands:``,
``notes:``.

The JSON schema (``--agentic-format json``) is now generated by
``core.agentic_schema.build_schema_json`` via ``BaseAssistant.maybe_emit_agentic``,
not hand-written here.
"""
from __future__ import annotations


APP_ID = "telemetry"
PURPOSE = "Claude Code session telemetry: cost, tokens, TUI, and OTel queries"

_COMMANDS: list[tuple[str, str]] = [
    ("live TUI dashboard", "./bin/telemetry live"),
    ("compact live stats", "./bin/telemetry stats --compact"),
    ("one-shot session summary", "./bin/telemetry summary"),
    ("recent sessions table", "./bin/telemetry history --days 7"),
    ("session cost/token table", "./bin/telemetry sessions --since 7d"),
    ("per-agent breakdown", "./bin/telemetry agents --since 7d"),
    ("cost by agent or day", "./bin/telemetry cost --since 7d --group-by agent"),
    ("classification rules", "./bin/telemetry rules --validate"),
    ("pre-parse transcripts", "./bin/telemetry parse-transcripts --since 7d"),
    ("query local OTel data", "./bin/telemetry otel --help"),
]

_NOTES: list[str] = [
    "`telemetry live` needs the [tui] extra (textual); stats/summary render via Rich and do not",
    "`cost` is an alias for `cost-breakdown`",
    "JSON output on sessions/agents/cost via --format json (parseable, stdout only)",
    "`otel` forwards remaining argv to telemetry.otel.cli; run `telemetry otel --help` for its subcommands",
]


def build_agentic_capsule() -> str:
    """Return the text/yaml capsule body."""
    lines: list[str] = []
    lines.append(f"agentic: {APP_ID}")
    lines.append(f"purpose: {PURPOSE}")
    lines.append("commands:")
    for label, cmd in _COMMANDS:
        lines.append(f"  - {label}: {cmd}")
    lines.append("notes:")
    for note in _NOTES:
        lines.append(f"  - {note}")
    return "\n".join(lines)


def build_agentic_capsule_compact() -> str:
    """Return a smaller capsule: drop the notes list."""
    lines: list[str] = []
    lines.append(f"agentic: {APP_ID}")
    lines.append(f"purpose: {PURPOSE}")
    lines.append("commands:")
    for label, cmd in _COMMANDS:
        lines.append(f"  - {label}: {cmd}")
    return "\n".join(lines)


def emit_agentic_context(  # NOSONAR S3516 - always returns 0 by design; callers chain return emit_agentic_context() as exit code
    _fmt: str = "text", compact: bool = False
) -> int:
    """Print the agentic capsule in the requested format and return exit code."""
    # text and yaml share the same hand-authored body — YAML-valid by construction.
    # JSON is handled by core.agentic_schema via BaseAssistant.maybe_emit_agentic.
    if compact:
        print(build_agentic_capsule_compact())
    else:
        print(build_agentic_capsule())
    return 0
